application: hellogaeapp
version: 3
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static
- url: /webapp2
  script: helloworld.app

- url: /tasks/checkapp/
  script: helloflask.app
  login: admin

- url: /.*
  script: helloflask.app

libraries:
- name: jinja2
  version: "2.6"

- name: lxml
  version: "latest"
