application: hellogaeapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /webapp2
  script: helloworld.app
- url: /.*
  script: helloflask.app

libraries:
- name: jinja2
  version: "2.6"

- name: lxml
  version: "latest"